### ISSUE TITLE
Ambiguous use of distinct()

### ISSUE THREAD

**Issue by codedbypm** [DeclarativeHub/ReactiveKit#178]
Using XCode 9.3 and ReactiveKit 3.8, I get the above issue when doing something like `query.distinct()` where query is defined as `Observable<String?>`

Candidates are 
```
public extension SignalProtocol where Element: Equatable {

  /// Emit first element and then all elements that are not equal to their predecessor(s).
  public func distinct() -> Signal<Element, Error> {
    return distinct(areDistinct: !=)
  }
}

public extension SignalProtocol where Element: OptionalProtocol, Element.Wrapped: Equatable {
  
  /// Emit first element and then all elements that are not equal to their predecessor(s).
  public func distinct() -> Signal<Element, Error> {
    return distinct(areDistinct: !=)
  }
}
```

Since now `Optional` conform to `Equatable`, the second extension can be removed and that would fix the issue. 
I have a PR ready but I do not see the any swift-4.1 branch that I could target.

**Comment by srdanrasic** [comment]
I've just released v3.9.1 that works with Swift 4.1. Sorry for the late reply and thanks for reporting this.
