### ISSUE TITLE
take(until:) behavior isn't consistent with its description

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/ReactiveKit#186]
# Problem description
As per the description provided in [SignalProtocol.swift](https://github.com/DeclarativeHub/ReactiveKit/blob/master/Sources/SignalProtocol.swift) it seems to me that `take(until:)` should only stop propagating elements from the receiver when the given signal emits a `.completed` event  : 

> /// Emit elements of the reciver until given signal completes and then complete the receiver.

However based on the tests I have done and the [source code](https://github.com/DeclarativeHub/ReactiveKit/blob/8ecab7819fb6d3086b41767d292f87333e47b70a/Sources/SignalProtocol.swift#L777), it appears that` take(until:)` will complete as soon as *any* event is emitted by the given signal.

```
  public func take<S: SignalProtocol>(until signal: S) -> Signal<Element, Error> {
    return Signal { observer in
      let disposable = CompositeDisposable()

      disposable += signal.observe { event in
        observer.completed()
      }
 ...
```

# Suggested Solution
So either the description should be changed to indicate that *any* event from the given receiver will stop the flow of events from the receiver, or the code should be changed to use : 

```
  public func take<S: SignalProtocol>(until signal: S) -> Signal<Element, Error> {
    return Signal { observer in
      let disposable = CompositeDisposable()

      disposable += signal.observeCompleted {
        observer.completed()
      }
 ...
```
Thanks,
N.

# Appendix
Here's the code I am using in a Swift Playground to test this out : 

```
print("Take UserSubject events until pausing with PauseSignal")
let userBag = DisposeBag()
let userSubject = PublishSubject<User, UserDetailError>()
let pauseSignal = SafePublishSubject<Bool>()
pauseSignal.debug().observe { _ in }.dispose(in: userBag)
pauseSignal.start(with: true)
userSubject.take(until: pauseSignal).observe { event in
    print("Observing UserSubject")
    print("--> \(event)")
    }.dispose(in: userBag)
userSubject.next(User(id: "123", username: "toto", displayName: "Toto Tata"))
userSubject.next(User(id: "456", username: "titi", displayName: "Titi Tutu"))
pauseSignal.next(true)
//pauseSignal.completed()
userSubject.next(User(id: "789", username: "tata", displayName: "Tata Tyty"))
userBag.dispose()
```

It doesn't matter if I use `pauseSignal.next(true)` or `pauseSignal.completed()` the next User (id=789) will not be printed.

**Comment by srdanrasic** [comment]
Yes, there seems to be an inconsistency. I commented on your PR.
