### ISSUE TITLE
Application freezes 

### ISSUE THREAD

**Issue by fruitcoder** [DeclarativeHub/ReactiveKit#190]
Yesterday I updated Bond and ReactiveKit to run with Xcode 9.3 (Swift 4.1) and noticed that my app freezed after just going from the main view controller to detail and back. Pausing the execution I see the following stack trace:

<img width="1680" alt="screen shot 2018-04-10 at 13 55 25" src="https://user-images.githubusercontent.com/5515849/38555742-957a38a6-3cc7-11e8-9c89-6e4bd699921a.png">

This seems to be the exact line that was added in [this PR](https://github.com/DeclarativeHub/ReactiveKit/pull/184/files). In fact, removing this very line makes the freeze go away. Do you have any idea what could cause this?

**Comment by tonyarnold** [comment]
Hi Alex, would you mind tracking back through the stack trace and finding out which of your observations this is happening with? Some sample code from your side would be immensely helpful - happy to do that in private if what you're working on is sensitive.

My gut feeling is that if this exception is happening when you're transitioning from your detail view controller back to your main view controller, there may be an observer that hasn't been properly disposed somewhere.

**Comment by fruitcoder** [comment]
Hi @tonyarnold, sorry I was on vacation and then sick. I will try to reproduce in a sample project first and otherwise contact you privately. What might be "special" in my case is that the signals get deallocated on a special queue by Texture (former ASDisplayKit). Maybe that's an issue

**Comment by fruitcoder** [comment]
Unfortunately, I haven't been able to reproduce it in a sample app yet (using a similar setup like my other app with Texture), but my main app is still freezing. I'll keep trying to reproduce and on the other hand commenting out code from my main app.

**Comment by fruitcoder** [comment]
Hi @srdanrasic! Sorry for the late reply. I just tested your fix branch and it doesn't freeze anymore 🎉

**Comment by AviadorC** [comment]
I'm facing exactly the same issue. Is there any possibility that fix/subject-lock will be merged soon?

**Comment by srdanrasic** [comment]
I just released v3.9.6 with a fix. Thanks everyone!
