### ISSUE TITLE
Please Help, I want to observe property, but seem to not work

### ISSUE THREAD

**Issue by MQL9011** [DeclarativeHub/ReactiveKit#214]
Here is my code

![image](https://user-images.githubusercontent.com/11871158/56089487-29d6f680-5ec6-11e9-990e-ff20bc9fd710.png)

I change the `playing` , but not print result.

**Comment by MQL9011** [comment]
I just want to observe the value `playing ` change

**Comment by srdanrasic** [comment]
You need to declare the instance property as a `Property`.

```swift
public let playing = Property(false)
```

then you can change it and observe:

```swift
playing.observeNext { ... }

playing.value = true
```

**Comment by MQL9011** [comment]
@srdanrasic  Thanks 

I solved this by

![image](https://user-images.githubusercontent.com/11871158/56104841-09617780-5f6c-11e9-8c8c-3c2dd834134e.png)

![image](https://user-images.githubusercontent.com/11871158/56104850-0fefef00-5f6c-11e9-918d-58c60cce84de.png)

Is this correct?

**Comment by srdanrasic** [comment]
That is correct. You are getting a warning because you are not handling the disposable. 

Learn more about it here:

https://github.com/DeclarativeHub/ReactiveKit/blob/master/README.md#disposing-signals

Alternatively, use bindings instead of observations.

**Comment by MQL9011** [comment]
@srdanrasic   Thank you very much.

Is there any example demo I can learn ?

**Comment by MQL9011** [comment]
I add the disposable like this.

![image](https://user-images.githubusercontent.com/11871158/56178632-8dcbfd00-6035-11e9-83ad-544a5ad0e1a6.png)

**Comment by makslevental** [comment]
@srdanrasic this might be a silly question but is there a way to observeNext a value that is mutated intrinsically? ie i mutate the value directly without going through Observable.value

**Comment by srdanrasic** [comment]
Unfortunately Swift doesn’t allow something like that natively. It would only work for KVO enabled properties. If that’s you case, then you could use Bond framework to observe such property. Check out the example here:

https://github.com/DeclarativeHub/Bond/blob/master/Playground-iOS.playground/Pages/Key%20Value%20Observing.xcplaygroundpage/Contents.swift
