### ISSUE TITLE
is there a deferred operator in ReactiveKit ?

### ISSUE THREAD

**Issue by ibrahimkteish** [DeclarativeHub/ReactiveKit#215]
I would like to have the deferred functionality in this library, as far as I know it doesn't exists or it does ?

here is the functionality of deferred
http://reactivex.io/documentation/operators/defer.html

**Comment by srdanrasic** [comment]
Is this something you had in mind?

```swift
extension Signal {

    public init<Other: SignalProtocol>(defer makeSignal: @escaping () -> Other) where Other.Element == Element, Other.Error == Error {
        self.init { observer in
            return makeSignal().observe(with: observer)
        }
    }
}


let deferred = SafeSignal<Int>(defer: {
    SafeSignal(just: 4)
})
```

**Comment by ibrahimkteish** [comment]
I will try it and get back to you, must probably this is what I need :) Thank you @srdanrasic
