### ISSUE TITLE
unwrap() has disappeared as part of v3.10.0

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/ReactiveKit#220]
### Context

**Note** : this is FYI only, to document my experience with `unwrap()` in the context of upgrading to 3.10.0 as this might be useful to others migrating up and facing the same issues.

After upgrading to v3.10.0 (and v.3.11.0) I noticed several issues around `unwrap()`. My code makes extensive use of `unwrap()` to flatten a signal of sequence into signals of elements of the sequence. After upgrading this didn't work anymore and the compiler complained about : 

> Value of type 'Signal<[String : User], ApplicationError>' has no member 'unwrap'

I was a little surprised since the [Release Notes in v.3.10.0](https://github.com/DeclarativeHub/ReactiveKit/releases/tag/v3.10.0) indicate the following

> The release is backward compatible.

### Resolution

Apparently based on #210, it appears that `unwrap()` has been replaced by `flattenElements()` as part of this particular commit : [Cleanup nested container APIs](https://github.com/DeclarativeHub/ReactiveKit/commit/c7bdebb1b2970db50e1fc466187cdc00de34a371)

So if you're faced with the `unwrap()` method not being available anymore after upgrading to 3.10.0 / 3.11.0, you'll need to replace all occurrences of that method by `flattenElements()`.

HTH.

**Comment by srdanrasic** [comment]
This is my bad, looks like I forgot to deprecate it. I'll add the following to the next release:

```swift
extension SignalProtocol where Element: Sequence {

    @available(*, deprecated, renamed: "flattenElements")
    public func unwrap() -> Signal<Element.Iterator.Element, Error> {
        return flattenElements()
    }
}
```

Thanks for reporting this!
