### ISSUE TITLE
How to turn a standard model class/struct into observable properties?

### ISSUE THREAD

**Issue by kevinrenskers** [DeclarativeHub/ReactiveKit#231]
Let's say I have a User model in my app. Something like this.

```
class User: Codable {
  var id: String?
  var firstName: String?
  var avatar: String?
}
```

The content comes from a remote API, by making it confirm to Codable everything works nice and easy.

But let's also say for example that I would like a bidirectional binding from a model property to some UI state; that is not possible since none of my properties confirm to the `BindableProtocol`. Or if I want to observe changes to my model's properties, this is not possible either of course.

So my question is: how do I turn my model properties in actual observable Properties, without breaking the existing User model and behavior? For example, it still needs to be Codable. Do I make a second ObservableUser class, and then have didSet in all properties on the User model to write changes to the ObservableUser? And something similar on the ObservableUser to write changes back to the User? That seems horrible and hopefully not the recommenced way forward.

It seemed that something like https://github.com/DeclarativeHub/ReactiveKit/pull/194 could've helped here (making Property codable), but that was closed. So what is the best way forward?

**Comment by srdanrasic** [comment]
This can now be implemented using `Published` property wrappers.

```
class User: Codable {
  var id: String?
  @Published var firstName: String?
  @Published var avatar: String?
}
```

It enables you to expose properties as signals like `user.$firstName.sink { print($0) }`.

**Comment by kevinrenskers** [comment]
That looks awesome! What is the difference between `sink` and `observeNext` by the way?

**Comment by srdanrasic** [comment]
It's pretty much the same, the only difference is that `sink` returns `AnyCancellable` that cancels the signal when it's deallocated, while `observeNext` returns `Disposable` that cancels the signal when `dispose()` is called on it.

`sink` is there because we are bringing ReactiveKit closer to Apple's Combine.

**Comment by kevinrenskers** [comment]
So instead of adding `.dispose(in: disposeBag)` to the `observeNext` chain, you'd need to store the `sink` in a local property, so it will be probably deallocated and thus cancelled?

**Comment by srdanrasic** [comment]
`AnyCancellable` also conforms to `Disposable` so you can use it like any other disposable, eg put it into a bag.
