### ISSUE TITLE
README.md misprint

### ISSUE THREAD

**Issue by andriymobilemailinator** [DeclarativeHub/ReactiveKit#232]
[https://github.com/DeclarativeHub/ReactiveKit/blob/master/README.md#subjects](url)

public final class ReplaySubject<Element, Error: Swift.Error>: Subject<Element, Error> {

  private var **buffer**: [Event<Element, Error>] = []

  public override func on(_ event: Event<Element, Error>) {
    **events**.append(event)
    super.on(event)
  }

  public func observe(with observer: @escaping Observer<Element, Error>) -> Disposable {
    buffer.forEach { observer($0) }
    return super.observe(with: observer)
  }
}

**Comment by svachmic** [comment]
Well spotted, feeling like submitting a PR?

**Comment by srdanrasic** [comment]
FIxed
