### ISSUE TITLE
Update to Swift 5.1.1 for Xcode 11.2

### ISSUE THREAD

**Issue by MaruthiBasava** [DeclarativeHub/ReactiveKit#233]

**Comment by frankschlegel** [comment]
My apps are crashing inside ReactiveKit code when creating any kind of binding or observation on a `Property` (possible any kind of signal) when built with Xcode 11.2. With Xcode 11.1 everything works fine.
A `EXC_BAD_ACCESS` is invoked when calling `observe(with:)` on `Signal`.

I uploaded a minimal example project to demonstrate the issue.
[ReactiveKitCrashTest.zip](https://github.com/DeclarativeHub/ReactiveKit/files/3801500/ReactiveKitCrashTest.zip)

Any ideas what might have changed in 11.2 to cause this?

**Comment by cre8it** [comment]
will this pull request be released any time soon, I manually overwrote the Subject.swift files with the one committed by @frankschlegel and it all works fine again.

**Comment by frankschlegel** [comment]
@cre8it Did you get the same issues (runtime crashes in Xcode 11.2)?

**Comment by srdanrasic** [comment]
Hey @frankschlegel , thank for looking into this. I've tried to dig deeper into what's causing the issue and it might be this: https://bugs.swift.org/browse/SR-11564.

Setting `DEAD_CODE_STRIPPING = NO` if using SPM seems to solve the problem. I guess we should add the build flag to ReactiveKit target so it works over Carthage as well.

**Comment by cre8it** [comment]
@frankschlegel Yes we experienced the same problem with 11.2 and your modification solved it. That been said soon after we experienced another EXC_BAD_ACCESS with Lottie for iOS (https://github.com/airbnb/lottie-ios/issues/1066) which we solved as mentioned by @srdanrasic by setting the DEAD_CODE_STRIPPIN to NO in our build settings... 

We patched the Subject.swift file with your version @frankschlegel but never tried to just and only alter the DEAD_CODE_STRIPPIN flag. We will try it tomorrow by just resetting ReactiveKit to its original state and the flag to NO

**Comment by srdanrasic** [comment]
@frankschlegel @cre8it how are you integrating ReactiveKit? CocoaPods, Carthage or SPM?

I'm experiencing this problem only when using SPM and setting `DEAD_CODE_STRIPPIN = NO` in the builds settings of the target that uses ReactiveKit seems to fix the problem.

**Comment by cre8it** [comment]
@srdanrasic indeed your assumption is correct, for our part we use SPM. The Lottie issue seems also to only happen via SPM

**Comment by frankschlegel** [comment]
@srdanrasic Amazing find! I didn't think of checking the Swift bug tracker.
And yes, I'm indeed using ReactiveKit via SPM. Trying `DEAD_CODE_STRIPPIN = NO` now.

**Comment by frankschlegel** [comment]
Disabling code stripping also solved the issue for me. 👍 
So you can most likely discard my PR and wait for the Swift team to fix the issue.

**Comment by frederic-c-dcode** [comment]
I felt like I had a bad dream this morning 😨 when I saw EXC_BAD_ACCESS in my project at ReactiveKit level, but I was reassured to see that I was not the only one, and that there is a solution to get around the problem while waiting for Apple to moves its ass!
