### ISSUE TITLE
Versions 3.14.1 & 3.14.2 not available via Cocoapods

### ISSUE THREAD

**Issue by AnthonyMillerSF** [DeclarativeHub/ReactiveKit#235]
It looks like these were never pushed to the trunk. 
https://github.com/CocoaPods/Specs/tree/master/Specs/5/9/5/ReactiveKit

Can we please get this pushed? Thanks!

**Comment by srdanrasic** [comment]
Thanks for reporting this @AnthonyMDev. I've pushed the latest version just now.

**Comment by AnthonyMillerSF** [comment]
Thanks @srdanrasic. You're the best, as always.
