### ISSUE TITLE
Make AnyCancellable conforms to Hashable

### ISSUE THREAD

**Issue by ibrahimkteish** [DeclarativeHub/ReactiveKit#241]
I was wondering if it is possible to make `AnyCancellable` implements `Hashable`, I am asking about that because `Combine's` AnyCancellable is conforming to `Hashable`

**Comment by ibrahimkteish** [comment]
Implemented in [#242](https://github.com/DeclarativeHub/ReactiveKit/pull/242)

**Comment by srdanrasic** [comment]
Thanks, it's merged in now. I'll publish a new version.
