### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by kevinrenskers** [DeclarativeHub/ReactiveKit#258]
It's stuck on 3.16.3.

**Comment by AnthonyMillerSF** [comment]
Yes please @srdanrasic! Think you just for got to do the `pod trunk push`! :)

**Comment by srdanrasic** [comment]
Sorry about that guys, it's release now on CocoaPods as well.

**Comment by AnthonyMillerSF** [comment]
Thanks @srdanrasic, saw you hadn't made updates in a few weeks and was afraid Coronavirus had gotten you! haha :P 
Appreciate all your work on this library!
