### ISSUE TITLE
Help resolving : Thread 2: EXC_BAD_ACCESS (code=2, address=0x7000077f4fb8)

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/ReactiveKit#260]
Hi,

This might be an old issue (rtfm) / easy to fix, but I couldn't find anything in the ReactiveKit archives ; and the Bond archives only had 1 hit that didn't yield anything for me.

Oh... and I am sure I am doing something wrong...

### Environment
Xcode 11.4.1
Testing on Simulator iOS v 13.4.1
"DeclarativeHub/Bond" "7.7.1"
"DeclarativeHub/ReactiveKit" "v3.17.1"

### Error
I get the following error : 

```
Thread 2: EXC_BAD_ACCESS (code=2, address=0x7000077f4fb8)
```

This shows up in the following thread when using `reloading(property:)` on a LoadingProperty. Specifically, the debugger is pointing at the following code in `AtomicObserver`  located in `Observer.swift` ([line 123](https://github.com/DeclarativeHub/ReactiveKit/blob/a45f218217175e7c933acc82681ec8ce62ec55a4/Sources/Observer.swift#L123) for v3.17.1)

```
Thread 2 Queue : NSOperationQueue 0x7fe352c12880 (QOS: UNSPECIFIED) (concurrent)

    public func dispose() {
        observerLock.lock()
        observer = nil
        observerLock.unlock()
        disposablesLock.lock()
        self.upstreamDisposables.forEach { $0.dispose() }               <-------- ERROR
        disposablesLock.unlock()
    }
```

### Context
My code essentially captures the tap in a cell of a UITableView that's bound to an Array2D.
For each category of participants (only 2 categories : driver or rider) the user can select / unselect whether each participant is opting in or out of a car pool.

Either way, we update the participant's status (all good until that point) and then (after the flatMapLatest) we reload the related services to make sure they get updated when we call on other views.

That's when the error shows up (see the arrow <-------)

```
...
                cell.reactive
                    .tapGesture()
                    .with(latestFrom: participant.selected.toSignal())
                    .flatMapLatest { arg -> Signal<Bool, ApplicationError> in
                        let (_, selected) = arg
                        switch indexPath.section {
                        case 0:
                            return carpoolService
                                .addDriverToCarPool(driverID: participant.user.localId,
                                                    selected: !selected )
                                .feedNext(into: participant.selected)
                        case 1:
                            return carpoolService
                                .addRiderToCarPool(riderID: participant.user.localId,
                                                   selected: !selected )
                                .debug()
                                .feedNext(into: participant.selected)
                                .debug()
                        default:
                            return Signal<Bool, ApplicationError>
                                .failed(ApplicationError("Somehow a new category of Car Pool participant has been generated"))
                        }
                    }
                    // We reload the event list to make sure the choice of partipation in
                    // a specific carpool is properly reflected in the events displayed
                    .debug()                                                                  // fine until that point
                    .reloading(carpoolService.carPools)                    // <-------  ERROR !!!
                    .debug()
                    .reloading(eventService.events)
                    .debug()
                    .suppressError(logging: true)
                    .bind(to: cell) { _, _ in }
```

Any help / pointers on how to debug this would be greatly appreciated.

**Comment by npvisual** [comment]
I looked at issue #233 which seemed to be the closest thing related to my problem. However : 

- I am not using SPM (using Carthage),
- the class where this problem is triggered (AtomicObserver) is `final`, generic and has private variables (which seem to match a comment made in [SR-11749](https://bugs.swift.org/browse/SR-11749), which is linked from [SR-11564](https://bugs.swift.org/browse/SR-11564)
- using `DEAD_CODE_STRIPPING = NO` does NOT solve the issue


Note : since I could be doing something wrong in setting `DEAD_CODE_STRIPPING = NO` in my project's target, I am attaching a screenshot of the config, just for kicks...

![Screen Shot 2020-04-23 at 10 11 55 AM](https://user-images.githubusercontent.com/3268395/80116088-25b6cd80-854b-11ea-96de-6eb552fa0873.png)

**Comment by srdanrasic** [comment]
Could it be that something else is mutating `carpoolService.carPools` at the same time? I've seen issue like this when violating access exclusivity (https://swift.org/blog/swift-5-exclusivity/).

**Comment by npvisual** [comment]
Well, the Array2D that holds those cell is updated via that `capoolService.carPools`. So maybe that's that.

If I don't `.reloading(carpoolService.carPools)` things work fine. So I am assuming that's what's causing the issue. But I am pretty sure I was doing that just fine before :( .

**Comment by npvisual** [comment]
Since the app didn't crash when I commented out the reloading calls, I decided to move them outside of the Array2D binding.

I first tried to use the `.lifecycleEvent(.viewWillDisappear)` inside the detail carpool view, but that triggered the same crash (same place in the code in AtomicObserver).

Since the goal was  to refresh 2 LoadingProperty items (carPools and events) I tried with the following the carpool list view : 

```
        controller.reactive
            .lifecycleEvent(.viewDidAppear)
            .debug()
            .flatMapLatest { eventService.events.reload() }
            .debug()
            .consumeLoadingState(by: controller)
            .bind(to: controller) { _, _ in }
```

This works, however, as soon as I re-introduce the carPools LoadingProperty (used, of course, in the carpool list view), I get the same EXC_BAD_ACCESS.

But I guess my question then, if that's not supposed to work, is how do you refresh the data in an Arrray2D that feeds a list view once you've modified an element (via a REST call in a remote DB for example) of that list in the element detail view ?

I mean you want the list to reflect the latest updates once you pop the edit view controller...

Am I making any sense ?

**Comment by npvisual** [comment]
Alright, so I think I found the problem.

In the EventService, and at some point in the CarPoolService, I was calling `.flatMapLatest` on a set of signals that would call out to one of the EventKit APIs, such as :

```
eventStore.calendarItems(withExternalIdentifier: externalID)
```

So when the upstream signals (async most likely) would need to get disposed, whatever was holding the reference had already been discarded (or something to that effect).

Replacing `.flatMapLatest` with `.flatMapConcat`, as it should have been, fixes the problem.

Here's an example : 
```
       let relevantEvents = relevantCalendarIDs
            // We use the liftValue() operator to operate directly on the signal
            // of calendar IDs array.
            .liftValue { signal in
                signal
                    .flatMapLatest { calids in                 <---------- NO !!!
                        // Return the list of events corresponding to the given subcalendar IDs
                        // for the given date interval.
                        calendarService
                            .getEventCollection(interval: DateInterval(start: Date(), duration: 604800.00),
                                                           calendarIds: calids.compactMap { $0 })
                }
```

I have since then modified quite a bit of the way I was handling the list of carpools and the associated events; calling `.reloading(carpoolService.carPools)` in the CarPool detail view now works again the way it used to work !

Thanks!

**Comment by srdanrasic** [comment]
Happy to hear that Nick!
