### ISSUE TITLE
Compilation issues with Xcode 12 Beta 4 ?

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/ReactiveKit#264]
Just starting to get the following issues on Xcode 12 Beta 4 (didn't happen with Beta 1, 2 and 3) when compiling dependencies in my project using Carthage : 

```
% carthage update --platform iOS
*** Fetching SwiftKeychainWrapper
*** Fetching Bond
*** Fetching ReactiveKit
*** Fetching Differ
*** Checking out SwiftKeychainWrapper at "3.4.0"
*** Checking out ReactiveKit at "v3.18.0"
*** Checking out Bond at "7.8.0"
*** Checking out Differ at "1.4.5"
*** xcodebuild output can be found in /var/folders/jr/yhtslrhn6_11_z3km5cygf6r0000gn/T/carthage-xcodebuild.88HWsC.log
*** Downloading Differ.framework binary at "Differ 1.4.5"
***  Skipped installing Differ.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.3 (swiftlang-1200.0.25.2 clang-1200.0.27.1)."

    Falling back to building from the source
*** Building scheme "Differ" in Differ.xcodeproj
*** Building scheme "ReactiveKit-iOS" in ReactiveKit.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/ReactiveKit/v3.18.0/Build/Intermediates.noindex/ArchiveIntermediates/ReactiveKit-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ReactiveKit.framework/ReactiveKit /xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/ReactiveKit/v3.18.0/Build/Products/Release-iphonesimulator/ReactiveKit.framework/ReactiveKit -output /xxxx/Documents/GitHub/turbopool/Carthage/Build/iOS/ReactiveKit.framework/ReactiveKit

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jr/yhtslrhn6_11_z3km5cygf6r0000gn/T/carthage-xcodebuild.88HWsC.log
```

However when I switch back to the previous Swift version, it works fine. So, basically, building with  Swift version 5.2.4 works, but not with Swift version 5.3.0**.

** Note :  this seemed to be working fine for Xcode 12 Beta prior to Beta 4.

**Comment by npvisual** [comment]
Apparently this is a problem with Carthage (see issue https://github.com/Carthage/Carthage/issues/3019) and seem to have been seen in Xcode 12 Beta 3 as well.

**Comment by srdanrasic** [comment]
@npvisual have you maybe tried running carthage with `--no-use-binaries` flag?

**Comment by npvisual** [comment]
@srdanrasic, thanks for your response. Yes, the issue isn't with the existing binaries. The install actually compiles everything from source (because of Differ's Swift version) and I get the same result with `--no-use-binaries`.

The problem is with `/usr/bin/xcrun lipo -create` and the architecture flags -- the error message isn't very indicative unfortunately. But if you separately run the command that's output under `Task failed with exit code 1:`, you'll see this error : 

> fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: <file X> and <file Y> ... have the same architectures (arm64) and can't be in the same fat output file.

The [link](https://github.com/Carthage/Carthage/issues/3019) I mentioned above, from Carthage, definitely shows this isn't an isolated case or a problem with ReactiveKit.

I'll go ahead and close this issue as there's a workaround included in the issue (though it's not fixed in Carthage).
